[package]
name = "bfjit"
version = "0.1.3"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2021"
license = "AGPL-3.0"
repository = "https://github.com/Nugine/bfjit"
description = "Brainfuck JIT VM tutorial"
keywords = ["brainfuck", "jit", "tutorial"]
categories = ["compilers", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.31"
dynasm = "2.0.0"
dynasmrt = "2.0.0"
clap = { version = "4.1.8", features = ["derive"] }
